version: '3'
services:
  db:
    #restart: always
    #image: mysql:5.7.18

    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Pmker123
      - MYSQL_DATABASE=liyade
      - MYSQL_USER=liyade
      - MYSQL_PASSWORD=Pmker123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
#    container_name: mysql-lable
#    volumes:
#      - ./mydir:/mydir
#      - ./datadir:/var/lib/mysql
#      - ./my.cnf:/etc/my.cnf
#      # 数据库还原目录 可将需要还原的sql文件放在这里
#      #- /apps/mysql/source:/docker-entrypoint-initdb.d
#    environment:
#      - "MYSQL_ROOT_PASSWORD=Pmker123"
#      - "MYSQL_DATABASE=liyade"
#      - "TZ=Asia/Shanghai"
#    ports:
#      # 使用宿主机的3306端口映射到容器的3306端口
#      # 宿主机：容器
#      - 3306:3306
